### ISSUE TITLE
Other Arduino STM32 repositories

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [avikde/koduino#1]
Hi,

I've just noticed your repo, and thought you may be interested in our repo which does Arduino for STM32F103 

See https://github.com/rogerclarkmelbourne/Arduino_STM32

Cheers

Roger Clark

**Comment by geosmall** [comment]
+1 on your recent STM32F303 variant work.  I am an M4 fan as well and keen to try your work http://www.stm32duino.com/viewtopic.php?p=11123#p11123

**Comment by avikde** [comment]
Hi @geosmall,
Indeed, I'm currently using a F301K6, F302R8, as well as an F303VC, so all of those definitely are supported. I think the "V" vs the R/C pin sizes have some significant differences, so if you have a F303CC chip, I'd begin with the "f301" variant currently on the repo, which basically works with F301/F302 in the <= 64-pin packages.

**Comment by geosmall** [comment]
Ok will do.  ThanksGeorge   On 03/05/16, Avik De<notifications@github.com> wrote: Hi @geosmall,Indeed, I'm currently using a F301K6, F302R8, as well as an F303VC, so all of those definitely are supported. I think the "V" vs the R/C pin sizes have some significant differences, so if you have a F303CC chip, I'd begin with the "f301" variant currently on the repo, which basically works with F301/F302 in the <= 64-pin packages.—Reply to this email directly or view it on GitHub.
