### ISSUE TITLE
Cannot get to run on Windows 10

### ISSUE THREAD

**Issue by gearhead** [avikde/koduino#26]
The installation instructions are a bit vague, but was able to pursue it a bit. 1) on Win10 (at least) i could not get anything to even start to work. The first problem I encountered was the need for Python. I got a message which indicates that python was missing on my install. It is not clear if it is 2.7 or 3.6, so I installed 2.7 as it is 'most stable'. The installations say nothing about Python, but apparently it is needed to upload code using the serial bootloader (Also no idea if this is correct, but it was the default selection). Also after python is installed, you need to install the serial library.

The second problem is that for whatever reason, the koduino package cannot go in C:\Users\username\Documents\Arduino\hardware. When I tried to compile the blink script using the 'serial stm32 loader' , I get an error: `python: can't open file 'C:\Program Files (x86)\Arduino/hardware/koduino/stm32/system/stm32loader.py': [Errno 2] No such file or directory`. Somewhere it appears to be hard coded to the C:\Program Files (x86)\Arduino\hardware directory. So I moved the koduino directory and tried again. Now I get this 
```
  File "C:\Program Files (x86)\Arduino/hardware/koduino/stm32/system/stm32loader.py", line 571, in <module>
    cmd.open(conf['port'], conf['baud'])
  File "C:\Program Files (x86)\Arduino/hardware/koduino/stm32/system/stm32loader.py", line 78, in open
    self.sp = serial.Serial(
AttributeError: 'module' object has no attribute 'Serial'
AttributeError: 'module' object has no attribute 'Serial'
```
Did a bit of googling on how the python script calls the serial library, but cannot go any further. Would love to try this out on my discovery board.

**Comment by avikde** [comment]
The error about the paths is confusing, but the python error seems like it just can't find the serial library. I usually do `pip install pyserial` and make sure to restart the terminals/programs

**Comment by avikde** [comment]
Closing assuming the problem got resolved.
