### ISSUE TITLE
Makefile project.mk does not work with spaces in the filename

### ISSUE THREAD

**Issue by avikde** [avikde/koduino#5]
Need some Makefile wizardry to fix this

**Comment by xxxajk** [comment]
No version of Make ever supported spaces in a filename. 
Make ignores quotes, so that isn't going to work either.
Your best bet is to use an underscore.

**Comment by avikde** [comment]
Whoops, well, thanks for the info. In the future I will suggest that users 
a) use the Arduino IDE, or
b) remove spaces from the path if they would rather use make

Thanks!
