### ISSUE TITLE
SerialUSB functionality

### ISSUE THREAD

**Issue by avikde** [avikde/koduino#7]
Need to implement and test this. First candidate will probably be F373 (have some old boards lying around with USB connected). Not sure what VID/PID should be used?

**Comment by xxxajk** [comment]
You would need to register for a VID block, which cost something like $5000.
I'm sure if you ask ST nicely, they can donate one to you. I know Atmel does this.
There is also an old business that has a VID block, and will give you a PID (or block of them) free if the project is 100% open source.
Details here:
http://wiki.openmoko.org/wiki/USB_Product_IDs

**Comment by rogerclarkmelbourne** [comment]
I've seen some boards that just use USB CDC use STM's default VID PID

BTW. its more complcated than just VID and PID, as to get microsoft to accept your VID's into windows its another big cost

Or you need to do the hack/ workaround that we had to use for the STM32, using locally generated digital certificates.

**Comment by avikde** [comment]
SerialUSB writing is now working on the F303 (F3 discovery board used to test) and F373 (tested on Maevarm M4), with support for optional USB disconnect pin. Serial reading has not been tested yet, and changing baud rates does not work (fixed at 115200). TODO: reading tests and support for other boards.
